name             'lib-tomcat'
maintainer       'TAMU Libraries'
maintainer_email 'helpdesk@library.tamu.edu'
license          'All rights reserved'
description      'Installs/Configures lib-tomcat'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.6.0'
depends          'ark'
depends          'java'
depends          'lib-task'
